services:
  - type: web
    name: pricedrop-backend
    env: python
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false